import { inject, provideAppInitializer } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

/**
 * Registers the heroicons outline/solid sprite sheets (generated by scripts/build-icons.mjs)
 * under the `heroicons_outline:*` / `heroicons_solid:*` namespaces used across every
 * Odivon design system template (e.g. [svgIcon]="'heroicons_solid:user-group'").
 */
export function provideOdivonIcons() {
  return provideAppInitializer(() => {
    const iconRegistry = inject(MatIconRegistry);
    const sanitizer = inject(DomSanitizer);

    iconRegistry.addSvgIconSetInNamespace(
      'heroicons_outline',
      sanitizer.bypassSecurityTrustResourceUrl('icons/heroicons-outline.svg'),
    );
    iconRegistry.addSvgIconSetInNamespace(
      'heroicons_solid',
      sanitizer.bypassSecurityTrustResourceUrl('icons/heroicons-solid.svg'),
    );
  });
}
